In [2]:
import tensorflow as tf
import os
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.metrics import mean_squared_error as mse
from sklearn.preprocessing import MinMaxScaler
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
df = pd.read_csv('timeseries.csv')


In [4]:
df = df.dropna(subset=['time']) 
df.tail(20)
df = df[:96431:]
# df['time'][78886]
df.index = pd.to_datetime(df['time'], format='%Y%m%d:%H%M')
df =  df.drop(["time","H_sun","T2m","WS10m","Int"], axis = 1)
df

G(i)
time                      
2010-01-01 00:07:00      0
2010-01-01 01:07:00      0
2010-01-01 02:07:00      0
2010-01-01 03:07:00      0
2010-01-01 04:07:00  91.98
...                    ...
2020-12-31 18:07:00      0
2020-12-31 19:07:00      0
2020-12-31 20:07:00      0
2020-12-31 21:07:00      0
2020-12-31 22:07:00      0

[96431 rows x 1 columns]

In [5]:
df["Seconds"] = df.index.map(pd.Timestamp.timestamp)
df

G(i)       Seconds
time                                    
2010-01-01 00:07:00      0  1.262304e+09
2010-01-01 01:07:00      0  1.262308e+09
2010-01-01 02:07:00      0  1.262312e+09
2010-01-01 03:07:00      0  1.262315e+09
2010-01-01 04:07:00  91.98  1.262319e+09
...                    ...           ...
2020-12-31 18:07:00      0  1.609438e+09
2020-12-31 19:07:00      0  1.609442e+09
2020-12-31 20:07:00      0  1.609445e+09
2020-12-31 21:07:00      0  1.609449e+09
2020-12-31 22:07:00      0  1.609452e+09

[96431 rows x 2 columns]

In [6]:
day  = 60 * 60 * 24
year =  365.2425 * day
month = 30 * day

df ["day sin"] = np.sin(df['Seconds'] * ( 2 * np.pi /day))
df ["day cos"] = np.cos(df['Seconds'] * ( 2 * np.pi /day))
# df ["year sin"] = np.sin(df['Seconds'] * ( 2 * np.pi /year))
# df ["year cos"] = np.cos(df['Seconds'] * ( 2 * np.pi /year))
df
  

G(i)       Seconds   day sin   day cos
time                                                        
2010-01-01 00:07:00      0  1.262304e+09  0.030539  0.999534
2010-01-01 01:07:00      0  1.262308e+09  0.288196  0.957571
2010-01-01 02:07:00      0  1.262312e+09  0.526214  0.850352
2010-01-01 03:07:00      0  1.262315e+09  0.728371  0.685183
2010-01-01 04:07:00  91.98  1.262319e+09  0.880891  0.473320
...                    ...           ...       ...       ...
2020-12-31 18:07:00      0  1.609438e+09 -0.999534  0.030539
2020-12-31 19:07:00      0  1.609442e+09 -0.957571  0.288196
2020-12-31 20:07:00      0  1.609445e+09 -0.850352  0.526214
2020-12-31 21:07:00      0  1.609449e+09 -0.685183  0.728371
2020-12-31 22:07:00      0  1.609452e+09 -0.473320  0.880891

[96431 rows x 4 columns]

In [7]:
df = df.drop(["Seconds"], axis = 1)
df.head(20)

G(i)   day sin   day cos
time                                            
2010-01-01 00:07:00        0  0.030539  0.999534
2010-01-01 01:07:00        0  0.288196  0.957571
2010-01-01 02:07:00        0  0.526214  0.850352
2010-01-01 03:07:00        0  0.728371  0.685183
2010-01-01 04:07:00    91.98  0.880891  0.473320
2010-01-01 05:07:00   432.28  0.973379  0.229200
2010-01-01 06:07:00   681.34  0.999534 -0.030539
2010-01-01 07:07:00   867.69  0.957571 -0.288196
2010-01-01 08:07:00   987.62  0.850352 -0.526214
2010-01-01 09:07:00  1034.38  0.685183 -0.728371
2010-01-01 10:07:00   998.94  0.473320 -0.880891
2010-01-01 11:07:00   887.09  0.229200 -0.973379
2010-01-01 12:07:00    702.6 -0.030539 -0.999534
2010-01-01 13:07:00   472.43 -0.288196 -0.957571
2010-01-01 14:07:00   208.97 -0.526214 -0.850352
2010-01-01 15:07:00        0 -0.728371 -0.685183
2010-01-01 16:07:00        0 -0.880891 -0.473320
2010-01-01 17:07:00        0 -0.973379 -0.229200
2010-01-01 18:07:00        0 -0.999534  0.030539
2010-01-01 19:07:00        0 -0.957571  0.288196

In [8]:
df = df[:96431:]
df_multi = df.iloc[:,0:5] # removing the time column 
df.tail(30)
print(df_multi.head(10))
print(df_multi.dtypes)
# y = [x for x in df['Int'] if x == 0.0]
# print(y)b
# type(df_multi)


                        G(i)   day sin   day cos
time                                            
2010-01-01 00:07:00        0  0.030539  0.999534
2010-01-01 01:07:00        0  0.288196  0.957571
2010-01-01 02:07:00        0  0.526214  0.850352
2010-01-01 03:07:00        0  0.728371  0.685183
2010-01-01 04:07:00    91.98  0.880891  0.473320
2010-01-01 05:07:00   432.28  0.973379  0.229200
2010-01-01 06:07:00   681.34  0.999534 -0.030539
2010-01-01 07:07:00   867.69  0.957571 -0.288196
2010-01-01 08:07:00   987.62  0.850352 -0.526214
2010-01-01 09:07:00  1034.38  0.685183 -0.728371
G(i)        object
day sin    float64
day cos    float64
dtype: object


In [9]:

df_multi['G(i)'] = pd.to_numeric(df_multi['G(i)'], errors='coerce')
unique_types = df_multi['G(i)'].apply(type).unique()

print(unique_types)

[<class 'float'>]


In [10]:

df_scaled = df_multi.to_numpy()


In [11]:

print(df_scaled[0:5,:]) # this it the input
print(df_scaled[5,:]) # this is the output

[[0.00000000e+00 3.05385132e-02 9.99533591e-01]
 [0.00000000e+00 2.88196268e-01 9.57571361e-01]
 [0.00000000e+00 5.26213924e-01 8.50352225e-01]
 [0.00000000e+00 7.28370970e-01 6.85182990e-01]
 [9.19800000e+01 8.80890738e-01 4.73319667e-01]]
[4.32280000e+02 9.73379258e-01 2.29200391e-01]


In [12]:
def df_to_X_y(df_as_np, window_size=5):
#   df_as_np = df.to_numpy()
  X = []
  y = []
  for i in range(len(df_as_np)-window_size):
    row = [a for a in df_as_np[i:i+window_size,:]]
    X.append(row)
    label = df_as_np[i+window_size,0]
    y.append(label)
  return np.array(X), np.array(y)

In [13]:
WINDOW_SIZE = 5
X1, y1 = df_to_X_y(df_scaled, WINDOW_SIZE)
print(X1[1])
print("slfejlksdjlfkjdslkjfjlk")
print(y1[0])
X1.shape, y1.shape

[[0.00000000e+00 2.88196268e-01 9.57571361e-01]
 [0.00000000e+00 5.26213924e-01 8.50352225e-01]
 [0.00000000e+00 7.28370970e-01 6.85182990e-01]
 [9.19800000e+01 8.80890738e-01 4.73319667e-01]
 [4.32280000e+02 9.73379258e-01 2.29200391e-01]]
slfejlksdjlfkjdslkjfjlk
432.28


((96426, 5, 3), (96426,))

In [14]:
X_train1, y_train1 = X1[:61367], y1[:61367]
X_val1, y_val1 = X1[61367:70127], y1[61367:70127] # 1 year for validation [61,367 , 70127]
X_test1, y_test1 = X1[70128:], y1[70128:] #  1 year testing [70,128 , 78887]
X_train1.shape, y_train1.shape, X_val1.shape, y_val1.shape, X_test1.shape, y_test1.shape


((61367, 5, 3), (61367,), (8760, 5, 3), (8760,), (26298, 5, 3), (26298,))

In [21]:
X_train1[:,:,0]

array([[  0.  ,   0.  ,   0.  ,   0.  ,  91.98],
       [  0.  ,   0.  ,   0.  ,  91.98, 432.28],
       [  0.  ,   0.  ,  91.98, 432.28, 681.34],
       ...,
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ]])

In [ ]:
print(np.mean(X_train1[:,:,0]))
np.std((X_train1[:,:,0]))
#  91.98, => -0.48
# 432.28 =>0.44

In [ ]:
g_training_mean = np.mean( X_train1[ : ,: ,0])
g_training_std = np.std( X_train1[ : ,: ,0])
def preprocess(X):
    X[:,:,0] = (X[:,:,0] - g_training_mean)/ g_training_std
    return X


In [ ]:
preprocess(X_train1)
preprocess(X_val1)
preprocess(X_test1)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam

model1 = Sequential()
model1.add(InputLayer((5, 3)))
model1.add(LSTM(64))
model1.add(Dense(8, 'relu'))
model1.add(Dense(1, 'linear'))

model1.summary()

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.01, patience=10, verbose=1, mode='min')

In [ ]:
cp1 = ModelCheckpoint('model_G(I)_TIME/', save_best_only=True)
# metrics , learning rate, loss  can be changed 
model1.compile(loss=MeanSquaredError(), optimizer=Adam(learning_rate=0.001), metrics=[RootMeanSquaredError()])

In [ ]:
model1.fit(X_train1, y_train1, validation_data=(X_val1, y_val1), epochs=50, callbacks=[cp1,early_stopping])

In [ ]:
from tensorflow.keras.models import load_model
model1 = load_model('model_G(I)_TIME/')

In [ ]:
train_predictions = model1.predict(X_train1).flatten()
train_results = pd.DataFrame(data={'Train Predictions':train_predictions, 'Actuals':y_train1.flatten()})
train_results.head(30)

In [ ]:
%matplotlib inline

import matplotlib.pyplot as plt
plt.plot(train_results['Train Predictions'][50:100])
plt.plot(train_results['Actuals'][50:100])

In [ ]:

val_predictions = model1.predict(X_val1).flatten()
val_results = pd.DataFrame(data={'Val Predictions':val_predictions, 'Actuals':y_val1.flatten()})
val_results.head(20)

In [ ]:
plt.plot(val_results['Val Predictions'][50:100],label)
plt.plot(val_results['Actuals'][50:100])

In [ ]:
test_predictions = model1.predict(X_test1).flatten()
test_results = pd.DataFrame(data={'Test Predictions':test_predictions, 'Actuals':y_test1.flatten()})
test_results

In [ ]:
from sklearn.metrics import mean_squared_error as mse

def plot_predictions1(model, X, y, start=50, end=100):
  predictions = model.predict(X).flatten()
  df = pd.DataFrame(data={'Predictions': predictions, 'Actuals':y})
  plt.plot(df['Predictions'][start:end])
  plt.plot(df['Actuals'][start:end])
  return df, mse(predictions, y)

In [ ]:
plot_predictions1(model1, X_test1, y_test1.flatten())

In [ ]:
df_multi.iloc[78889:78920,:]

In [ ]:
kkk = df_multi.iloc[78885:78890,:]
time = str(df_multi.index[78889])
print(time)
print(type(kkk))
print(kkk.shape)
reshaped_array = np.reshape(kkk.to_numpy(), (1, 5, 3))
preprocess(reshaped_array)
print(reshaped_array)
predictions = model1.predict(reshaped_array)
print(predictions[0][0])

# original= scaler.inverse_transform(predictions)
# print(original)
# predictions
# inverse_data = np.zeros((len(predictions), scaler.shape[1]))

In [ ]:
from datetime import datetime, timedelta

def get_next_24_hours_from_datetime(start_datetime_str):
    """
    Generate a list of strings representing the datetime for the next 24 hours,
    given the start datetime in the format "YYYY-MM-DD HH:MM:SS".

    Parameters:
    - start_datetime_str (str): The starting datetime in the format "YYYY-MM-DD HH:MM:SS".

    Returns:
    - list of strings: Each string contains the datetime for the next 24 hours in the format "YYYY-MM-DD HH:MM:SS".
    """
    # Convert the input string to a datetime object
    start_datetime = datetime.strptime(start_datetime_str, "%Y-%m-%d %H:%M:%S")

    # Initialize a list to hold the future datetimes in the desired format
    future_datetimes_formatted = []
    day_sin= []
    day_cos= []

    # Calculate and format the next 24 hours
    for i in range(2, 26):  # Start from 1 to include the next hour immediately
        future_datetime = start_datetime + timedelta(hours=i)
        timeStamp = future_datetime.timestamp()
        day_sin_ = np.sin(timeStamp * ( 2 * np.pi /day))
        day_cos_ = np.cos(timeStamp * ( 2 * np.pi /day))
        day_sin.append(day_sin_)
        day_cos.append(day_cos_)
        
    return day_cos,day_sin


In [ ]:
day_cos, day_sin = get_next_24_hours_from_datetime(time)

In [ ]:

input = df_scaled[78885:78890,:]  # Initial input extracted from your original scaled DataFrame
output_scaled = []  
output_not_scaled = [] 

for i in range(24):
    # Reshape input for the model prediction
    reshaped_array = np.reshape(input, (1, 5, 3))
    preprocess(reshaped_array)
    prediction = []
    prediction.append( model1.predict(reshaped_array)[0][0])
    prediction.append(day_sin[i])
    prediction.append(day_cos[i])
    
    
    
    # Reshape the prediction to match the input shape if necessary
    # Adjust the reshaping based on the actual shape of your model's output
    prediction_reshaped = np.reshape(prediction, (1, 3))
    input = np.reshape(input, (5, 3))  # Ensure input is in the correct shape before appending
    # Append the new prediction at the end of the input array
    input = np.vstack([input, prediction_reshaped])  # Stack vertically to add as a new row
    
    # Remove the oldest entry to maintain the sliding window of input data
    input = input[1:, :]  # Keep the last 5 entries, including the newly added prediction
    
    output_scaled.append(prediction[0])


# print(output_scaled)  # Remains empty, uncomment if needed
print(output_scaled)  # Print or process the predictions as 




In [ ]:
print("this is the real scaled output")
for i in output_scaled:
    print(i)